### ISSUE TITLE
Component is not being created in Redwood/Sumac

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/RecommenderXBlock#87]
### Expected behavior

Recommender xblock should be created.

### Actual behavior

When a recommender component is added nothing happens. When the page is refreshed on studio the page won't load. From LMS an error is displayed.

You can see it here (until next Monday): https://studio.redwood.demo.edly.io/container/block-v1:OpenedX+DemoX+DemoCourse+type@vertical+block@19fc1913a7f64ce4a4223e9f314cedef

[Screencast from 23-05-24 09:51:20.webm](https://github.com/openedx/RecommenderXBlock/assets/64440265/e6624bed-7ee3-44f0-bb92-c2c1922cc672)

### Steps to reproduce

Go to Studio, add "recommender" to "Advanced Settings" -> "Advanced module list" add a component from "Advanced" -> "recommender"

Original issue: https://github.com/openedx/wg-build-test-release/issues/355

**Comment by mariajgrimaldi** [comment]
Hi @navinkarkera! I see you're the new maintainer. Could you give us a hand here? Thanks!

**Comment by navinkarkera** [comment]
@mariajgrimaldi I don't have write access yet as I just closed the nomination post. I'll need to sort out the permissions first, but I can take a look in the meantime.

**Comment by navinkarkera** [comment]
@mariajgrimaldi I just tried this xblock on tutor-nightly and it seems to work, although it doesn't look very good. I am not sure if I can get redwood stack working locally via tutor as of now.

![image](https://github.com/openedx/RecommenderXBlock/assets/10894099/d071fbd5-6490-4cf9-8f00-2b3c9a322b52)

**Comment by mariajgrimaldi** [comment]
Thank you for trying it! Was that tutor-nightly a remote environment? I'm just making sure the error is not related to an asset-production issue.

**Comment by navinkarkera** [comment]
> Was that tutor-nightly a remote environment?

@mariajgrimaldi No, tested it locally.

**Comment by mariajgrimaldi** [comment]
@navinkarkera: I tested it locally on Redwood, and it worked. So this might be related to how it's being deployed, maybe to the assets-building process? I don't know this component so I couldn't say for sure, but this is the error I'm seeing in the Studio console after replicating what I mentioned above:
```
Uncaught SyntaxError: invalid regular expression flag t
    globalEval https://studio.redwood.demo.edly.io/static/studio/js/cms-base-vendor.5fa9e818ccd4.js:486
    domManip https://studio.redwood.demo.edly.io/static/studio/js/cms-base-vendor.5fa9e818ccd4.js:5434
    append https://studio.redwood.demo.edly.io/static/studio/js/cms-base-vendor.5fa9e818ccd4.js:5574
    loadResource https://studio.redwood.demo.edly.io/static/studio/bundles/js/factories/container.33125aa522f51f597b81.ab77e4b3456f.js:2
    i https://studio.redwood.demo.edly.io/static/studio/bundles/js/factories/container.33125aa522f51f597b81.ab77e4b3456f.js:2
    i https://studio.redwood.demo.edly.io/static/studio/bundles/js/factories/container.33125aa522f51f597b81.ab77e4b3456f.js:2
    fire https://studio.redwood.demo.edly.io/static/studio/js/cms-base-vendor.5fa9e818ccd4.js:3330
    add https://studio.redwood.demo.edly.io/static/studio/js/cms-base-vendor.5fa9e818ccd4.js:3389
```

**Comment by navinkarkera** [comment]
@mariajgrimaldi It might be due underscore.min.js file as that is the only file which has regex with `t` flag which according to mozilla is not a valid flag (I am not even sure that is the issue here but doesn't hurt to try). The use of underscore.min.js was removed via this commit: https://github.com/openedx/RecommenderXBlock/commit/40bd60d643c82c8f3bbe2e2546b852c7d3ce32af so it should be safe to remove the file completely.

**Comment by navinkarkera** [comment]
@mariajgrimaldi Were you able to get this working?

**Comment by mariajgrimaldi** [comment]
@navinkarkera: thank you for all the insight. I haven't had the time to review this, but I'll try to get someone from my team to look. Thank you!

**Comment by BryanttV** [comment]
Hi @mariajgrimaldi @navinkarkera, I'm working on this issue. I will first try deleting the file that may be causing the error.

**Comment by BryanttV** [comment]
I tested in a remote environment on Redwood **(18.1.2)**. I installed a custom version that doesn't include the `underscore.min.js` file. However, it still keeps the same error, and this comes up in the browser console:
```js
VM591:1 Uncaught SyntaxError: Invalid regular expression flags
    at eval (<anonymous>)
    at Function.globalEval (cms-base-vendor.5fa9e818ccd4.js:486:5)
    at domManip (cms-base-vendor.5fa9e818ccd4.js:5434:15)
    at jQuery.fn.init.append (cms-base-vendor.5fa9e818ccd4.js:5574:10)
    at child.loadResource (container.33125aa522f51f597b81.ab77e4b3456f.js:2:97554)
    at i (container.33125aa522f51f597b81.ab77e4b3456f.js:2:97120)
    at Object.<anonymous> (container.33125aa522f51f597b81.ab77e4b3456f.js:2:97192)
    at fire (cms-base-vendor.5fa9e818ccd4.js:3330:31)
    at Object.add [as done] (cms-base-vendor.5fa9e818ccd4.js:3389:7)
    at i (container.33125aa522f51f597b81.ab77e4b3456f.js:2:97175)
```
I will continue to investigate what may be causing the error.

**Comment by BryanttV** [comment]
Hi, sorry for not updating the status of this. I spent some more time researching and found the following:

1. For Redwood (v18.1.2) on local and remote with [this branch](https://github.com/openedx/RecommenderXBlock/compare/master...BryanttV:RecommenderXBlock:bav/remove-underscore-js-file) which removes the `underscore.min.js` file from XBlock, the same error also happens.
2. For Nightly and v2.2.0 of XBlock, it works correctly locally.
3. Finally, with Redwood (v18.1.3 and v18.1.2) I tried an `edx-platform` mount with the `master` branch, and it works.

As a conclusion, the problem seems to be directly in `edx-platform`. In the `master` branch it seems to be already fixed.

**Comment by navinkarkera** [comment]
@BryanttV Thank you for you investigation!

@mariajgrimaldi Should we close this issue now that it has been fixed in master branch of edx-platform?

**Comment by BryanttV** [comment]
Hi, @mariajgrimaldi, @navinkarkera

We have been testing on:
- https://sandbox.openedx.edly.io/
- https://next-release.openedx.org/

![image](https://github.com/user-attachments/assets/f0c33000-ea5a-4949-b075-37603a3b511a)

The error is still present. Since these environments are not aligned with the latest changes in the `edx-platform`, the ideal would be to test in a remote environment in **Nightly**; however, we do not have access to one now. It's best to leave the issue open and monitor it in **Sumac** when it becomes available.

**Comment by mariajgrimaldi** [comment]
@BryanttV: have you been able to reproduce this issue in the sumac sandbox?

**Comment by BryanttV** [comment]
Hi @mariajgrimaldi, I have bad news. The error keeps happening in the Sumac sandbox :thinking: I'm running out of ideas about what might happen.

![image](https://github.com/user-attachments/assets/f4dfdb14-18ce-4e50-bc98-21619f101da0)

**Comment by mariajgrimaldi** [comment]
@navinkarkera, could you help us by looking into this issue? It seems like this xblock is unusable in remote environments.

**Comment by navinkarkera** [comment]
@BryanttV I don't have a remote environment to test this on but I have created this PR: https://github.com/openedx/RecommenderXBlock/pull/105 that removes use of mustache templates and replaces it with edx.HtmlUtils.template (which is what is used in edx-platform) and also upgrades tooltipster. Can you please test this PR branch in your remote environment and see if it fixes the issue?
cc: @mariajgrimaldi

**Comment by mariajgrimaldi** [comment]
Hi @navinkarkera! What did you find when testing https://github.com/openedx/edx-platform/pull/35899? 👀

**Comment by navinkarkera** [comment]
@mariajgrimaldi Same issue with latest master 😢 I tried playing with disabling parts like intro, tooltips, etc. but it did not help. I plan to mimic production setup locally and test but could find the time to do it. Let me know if you have any resources about it.

**Comment by efortish** [comment]
Hello @mariajgrimaldi  @navinkarkera , I just tried in sumac with tutor local and it is working without problem

**Comment by mariajgrimaldi** [comment]
@efortish: can you be more specific about what you did? Thanks!

@navinkarkera: what were you thinking about replicating a production environment locally? Would `tutor local` be enough? Which as mentioned above, it wasn't as productive either :/

**Comment by navinkarkera** [comment]
@mariajgrimaldi 😢 I am running out of ideas.
I can only think of rewriting the whole xblock part by part.

**Comment by efortish** [comment]
> [@efortish](https://github.com/efortish): can you be more specific about what you did? Thanks!

Hello @mariajgrimaldi , I added the recommender component in Sumac in a `tutor local` environment, everything seems good, the component was successfully added:

![Image](https://github.com/user-attachments/assets/6a376b64-5c5c-4cc1-873f-a419050be628)

**Comment by mariajgrimaldi** [comment]
@navinkarkera: I came back again to tooltipster with the devs tool in Chrome by stopping just before it failed. Can we test completly dropping it? 

![Image](https://github.com/user-attachments/assets/bf3f36e6-1a41-47a1-9dfd-a43d8228e821)
![Image](https://github.com/user-attachments/assets/374e4860-2b3d-4f48-b5df-74f688c805b1)

**Comment by navinkarkera** [comment]
@mariajgrimaldi Cool, I can try removing it but don't really have much time until Teak release.

**Comment by mariajgrimaldi** [comment]
@navinkarkera: we have a failure report for teak https://github.com/openedx/wg-build-test-release/issues/355#issuecomment-2841433221. Would you be able to look into it before teak.1?

**Comment by navinkarkera** [comment]
@mariajgrimaldi I'll look into it.

**Comment by navinkarkera** [comment]
@mariajgrimaldi I finally managed to find the root cause. The block is working in this [sandbox](https://app.pr-36672-0e7f8a.sandboxes.opencraft.hosting/learning/course/course-v1:UNIX+UX1+2025_T2/block-v1:UNIX+UX1+2025_T2+type@sequential+block@f1382dd2b74846aaada755aa5547f569/block-v1:UNIX+UX1+2025_T2+type@vertical+block@d651e3dba8de4187b94f8489b38c818a) (image upload does not work).

There are two different errors:

1. This [line](https://github.com/openedx/RecommenderXBlock/blob/5508e314b396877463a74d2a6fbb429ceb1b4c63/recommender/recommender.py#L1007) that includes i18n script incorrectly used `add_javascript` instead of `add_javascript_url`. It included something like below in html file:
```html
<script>
/static/js/xblock.v1-i18n/recommender/en.00d295569567.js
</script>
```
2. Use of `@XBlock.needs('fs')`. I am not sure why but using this fails in sandbox environments with follow error:
```log
Traceback (most recent call last):
  File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/common/djangoapps/util/views.py", line 63, in inner
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/views/decorators/clickjacking.py", line 58, in wrapper_view
    resp = view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/lms/djangoapps/courseware/views/views.py", line 1714, in render_xblock
    fragment = block.render(requested_view, context=student_view_context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/xblock/core.py", line 818, in render
    return self.runtime.render(self, view, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/xmodule/x_module.py", line 997, in render
    return super().render(block, view_name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/xblock/runtime.py", line 823, in render
    frag = view_fn(context)
           ^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/xmodule/vertical_block.py", line 204, in student_view
    return self._student_or_public_view(context, STUDENT_VIEW)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/xmodule/vertical_block.py", line 131, in _student_or_public_view
    rendered_child = child.render(view, child_block_context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/xblock/core.py", line 818, in render
    return self.runtime.render(self, view, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/xmodule/x_module.py", line 997, in render
    return super().render(block, view_name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/xblock/runtime.py", line 827, in render
    updated_frag = self.wrap_xblock(block, view_name, frag, context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/xmodule/x_module.py", line 949, in wrap_xblock
    frag = wrapper(block, view, frag, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/edx-platform/openedx/core/lib/xblock_utils/__init__.py", line 323, in add_staff_markup
    field_contents.append((name, field.read_from(block)))
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/xblock/fields.py", line 660, in read_from
    return self.__get__(xblock, xblock.__class__)  # pylint: disable=unnecessary-dunder-call
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/xblock/reference/plugins.py", line 141, in __get__
    value = xblock.runtime.service(xblock, 'fs').load(self, xblock)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/xblock/reference/plugins.py", line 192, in load
    return djpyfs.get_filesystem(scope_key(instance, xblock))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/djpyfs/djpyfs.py", line 45, in get_filesystem
    return get_osfs(namespace)
           ^^^^^^^^^^^^^^^^^^^
  File "/openedx/venv/lib/python3.11/site-packages/djpyfs/djpyfs.py", line 111, in get_osfs
    os.makedirs(full_path)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 5 more times]
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/edx'
```
@kaustavb12 Would you be able to help with above error? `XBlock.needs('fs')` fails with permission error in sandboxs.

**Comment by navinkarkera** [comment]
Created https://github.com/openedx/RecommenderXBlock/pull/111 to fix error number 1.

**Comment by navinkarkera** [comment]
`XBlock.needs('fs')` fails due to incorrect [DJFS setting](https://github.com/open-craft/edx-platform/blob/8680a280a83244a2b5cf1f4a03d0aad89e2c01d4/lms/envs/common.py#L1483-L1487).

```python
DJFS = {
    'type': 'osfs',
    'directory_root': '/edx/var/edxapp/django-pyfs/static/django-pyfs',
    'url_root': '/static/django-pyfs',
}
```

I have temporarily updated this setting in sandbox directly (it will be lost on next deployment) as below:

```python
DJFS = {
    'type': 'osfs',
    'directory_root': '/openedx/staticfiles/djpyfs',
    'url_root': '/static/djpyfs',
}
```
